### ISSUE TITLE
Cura 2.4

### ISSUE THREAD

**Issue by probonopd** [markwal/Cura-OctoPrintUpload#3]
Can this be made to work with Cura 2.4?

**Comment by netlands** [comment]
I am using the plugin successfully with **Cura 2.4.0** on Windows and **OctoPrint Version 1.3.1** (master branch). 
Setup via the **Extensions** menu  > **OctoPrint** > **OctoPrint Servers**. 
If **Save to OctoPrint** is not visible in the lower right corner after slicing, try clicking the drop-down arrow to the right of **Save to File**.

**Comment by markwal** [comment]
Should work now.
