### ISSUE TITLE
when i try to send to octoprint i get the following error

### ISSUE THREAD

**Issue by cnlson** [markwal/Cura-OctoPrintUpload#4]
cura 2.5
raspberry pi zero w
octoprint 0.14 latest
wanhao duplicator i3

could not save to octoprint: error tranferring http://192.168.1.165/api/files/local -  server replied:INTERNAL SERVER ERROR

![image](https://user-images.githubusercontent.com/1442027/28151707-e32b2baa-6761-11e7-8065-a5060121f973.png)

[octoprint.log.txt](https://github.com/markwal/Cura-OctoPrintUpload/files/1144129/octoprint.log.txt)

**Comment by markwal** [comment]
How big of a file?

Is a small file successful?

**Comment by cnlson** [comment]
One was a pi case so not very big. I'm wondering if it's a permission issue

**Comment by markwal** [comment]
We're you able to upload it the old way. That is, save to file and then upload via octoprint's web page?

Also, you should check your octoprint log since a servererror response will probably have an exception thrown logged there.

**Comment by cnlson** [comment]
I included it in my post. I'm not sure what to look for.

And yes, I can drag and slice or drop a sliced file in the page.

On Jul 13, 2017 10:13 AM, "Mark Walker - notifications@github.com"
<github.cnlson.f422ac2bc3.notifications#reply@reply.github.com> wrote:

We're you able to upload it the old way. That is, save to file and then
upload via octoprint's web page?

Also, you should check your octoprint log since a servererror response will
probably have an exception thrown logged there.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/markwal/Cura-OctoPrintUpload/issues/4#issuecomment-315108468>,
or mute the thread

**Comment by markwal** [comment]
Ah, I missed that little link at the end.  Sorry about that.  OK.  The log shows the exception clearly.

Though I'm not clear on why the filemanager ends up with a null entry.  What is the "title" of your print?  It's the name in the lower right hand corner of the Cura screen.  It's also the default filename when you choose to save to a file.  Perhaps OctoPrint doesn't like the filename I generated for some reason.

**Comment by cnlson** [comment]
because it is gcode rather than gco? if so that makes sense. although the
printer itself works with .gcode

**Comment by markwal** [comment]
From examining the code, it could be that it is uploading with no extension in the name or an extension isn't recognized by OctoPrint.  gcode and gco should be fine, but perhaps your name has an extra period in it, a space or an international character.

**Comment by markwal** [comment]
I use the same upload api that OctoPrint itself does, so it must be that the name I'm generating isn't as good for some reason as the one you upload manually.

**Comment by cnlson** [comment]
ok i am naming them with a full and normal name
