### ISSUE TITLE
updating to 2.7 octoprint servers not in menu

### ISSUE THREAD

**Issue by cnlson** [markwal/Cura-OctoPrintUpload#5]
I just downloaded 2.7 and octoprint servers is not in the menu to configure. Any suggestions? I still have 2.6.2 installed and it works wonderfully. nothing has moved, all i did was install 2.7

2.6.2
![image](https://user-images.githubusercontent.com/1442027/30096196-b8bd790c-929c-11e7-9e2f-f46f529bebb9.png)

the folder
![image](https://user-images.githubusercontent.com/1442027/30096201-c37c57f0-929c-11e7-9c51-15a0635ea57c.png)

the subfolder
![image](https://user-images.githubusercontent.com/1442027/30096213-d52e6466-929c-11e7-926d-8f55937ca969.png)

2.7 extensions
![image](https://user-images.githubusercontent.com/1442027/30096222-e0b08c60-929c-11e7-8b29-68c3eb893638.png)

**Comment by cnlson** [comment]
just noticed, in the plugins settings dialog there is a difference as well

2.6.2
![image](https://user-images.githubusercontent.com/1442027/30096291-387c2fbc-929d-11e7-85dc-ad8ce53bf5e2.png)
2.7
![image](https://user-images.githubusercontent.com/1442027/30096295-3f88df4e-929d-11e7-9efb-6d2f46ddd672.png)

**Comment by BerndJM** [comment]
The reason is:
for Cura 2.7 Plugins need a file "plugin.json" in their particular plugin folder.
Just unzip the attached file and copy it into the OctoPrintUpload folder.
 
[plugin.json.zip](https://github.com/markwal/Cura-OctoPrintUpload/files/1384171/plugin.json.zip)

**Comment by cnlson** [comment]
that worked perfectly! there is an upload and print feature in cura 2.7 but when i want to stack up a few models to print it doesn't work since it will only print one at a time. upload to cura works perfectly

**Comment by markwal** [comment]
Current master is now compatible with Cura 3.6
