### ISSUE TITLE
Upload to Repetier Server instead of octoprint

### ISSUE THREAD

**Issue by Technology89** [markwal/Cura-OctoPrintUpload#9]
Hi, i am running Repetier-Server for 4 printers. I normaly use S3D but sometimes i like to use cura. But there seems to be no plugin to do it. So i downloaded your plugin and had a look at the code (I have no idea about phyton) and got it somehow working. There were 2 lines i changed and maybe u could tell me if i actually got it the right way or if i should change something else. Maybe this could help some other guys with Repetier-Server but i want to make sure i am not doing some weird stuff here.

formvalues = {'select': 'false', 'print': 'false'}
changed to
formvalues = {'a': 'upload'}

self._request = QtNetwork.QNetworkRequest(QUrl(self._host + "/api/files/local")) 
changed to
self._request = QtNetwork.QNetworkRequest(QUrl(self._host))

Now i just added http://THE.IP.0.0:3344/printer/model/PRINTERNAME as server and added the api-key for repetier and it worked.

**Comment by markwal** [comment]
Hey, neat.  That seams reasonable to me.  (I don't know anything about Repetier-Server, but it seems likely that you did it correctly.  Thanks for posting this.
